### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by Piplopp** [Aluriak/munin#13]
Why did it load `DEFAULT_CONFIG` even when the `config.json` file is loaded ?
Seems to have no issue while not loading this.

**Comment by Aluriak** [comment]
As shown [here](https://github.com/Aluriak/munin/blob/master/munin/config/config.py#L80), the default config, the CLI config and the file config are all used in order to populate a [ChainMap](https://docs.python.org/3.6/library/collections.html#collections.ChainMap).

This mecanism is here to provide a priority system (CLI over file, file over default).

**Comment by Piplopp** [comment]
Oh, I understand thanks :+1:
